spring:
  application:
    name: customer-service
  data:
    mongodb:
      username: paccy
      password: paccy
      host: localhost
      port: 27071
      database: customer
      authentication-database: admin


server:
  port: 8070
